pretrained: backup/vanilla-f1/best_metric_F1.pth
metric:
  - name: Accuracy
    args:
  - name: F1
    args:
      nclasses: 8
  - name: AUC
    args:
      nclasses: 8
  - name: ConfusionMatrix
    args:
      nclasses: 8
dataset:
  name: SHREC21_RCHO_Rings_RenderOnly
  args:
    csv_path: data/datasetShape/list/1_val.csv
    root: data/datasetShape/generated_train
    ring_ids: [1, 3, 5]
    is_train: False
  loader:
    name: DataLoader
    args:
      num_workers: 8
      batch_size: 4
      pin_memory: True
