id: culture-masked-f1
pretrained: null
seed: 3698
model:
  name: BaseClassifier
  args:
    extractor_cfg:
      name: Base3DObjectRingsExtractor
      args:
        nheads: 4
        dropout: 0.1
        nrings: 3
        ring_ext_cfg:
          name: BaseRingExtractor
          args:
            hidden_dim: 512
            extractor_cfg:
              name: ImageMaskExtractor
              args:
                ext_cfg:
                  name: ResNetExtractor
                  args:
                    version: resnet50
                    is_frozen: True
                    use_pretrained: True
    nclasses: 6
optimizer:
  name: Adam
  args:
    lr: 0.00001
loss:
  name: CrossEntropyLoss
  args:
    weight: [2, 1, 6, 18, 2, 3]
metric:
  - name: F1
    args:
      nclasses: 6
scheduler:
  name: ReduceLROnPlateau
  args:
    mode: min
    factor: 0.5
    patience: 5
    verbose: True
dataset:
  train:
    name: SHREC21_RCHO_Rings_RenderMask
    args:
      csv_path: data/datasetCulture/list/1_train.csv
      root: data/datasetCulture/generated_train/
      ring_ids: [1, 3, 5]
      is_train: True
    loader:
      name: DataLoader
      args:
        num_workers: 8
        batch_size: 16
        shuffle: True
        pin_memory: True
  val:
    name: SHREC21_RCHO_Rings_RenderMask
    args:
      csv_path: data/datasetCulture/list/1_val.csv
      root: data/datasetCulture/generated_train/
      ring_ids: [1, 3, 5]
      is_train: False
    loader:
      name: DataLoader
      args:
        num_workers: 8
        batch_size: 16
        pin_memory: True
trainer:
  nepochs: 50
  val_step: 1
  log_step: 1
  log_dir: runs
