id: SHREC21-RCHO
pretrained: null
seed: 3698
model:
    name: BaseClassifier
    args:
        extractor_cfg: 
            name: Base3DObjectRingsExtractor
            args:
                nheads: 4
                nrings: 3
                ring_ext_cfg: 
                    name: BaseRingExtractor
                    args:
                        hidden_dim: 512
                        extractor_cfg:
                            name: ResNetExtractor
                            args:
                                version: resnet18
        nclasses: 8
optimizer:
    name: Adam
    args:
loss:
    name: CrossEntropyLoss
    args:
metric:
    - name: Accuracy
      args:
          nclasses: 8
scheduler:
    name: ReduceLROnPlateau
    args:
        mode: min
        factor: 0.5
        patience: 5
        verbose: True
dataset:
    train:
        name: SHREC21_RCHO_Rings_RenderOnly
        args:
            csv_path: data/list/shape/1_train.csv
            root: data/shape-train-rings/
            ring_ids: [0, 3, 6]
            is_train: True
        loader:
            name: DataLoader
            args:
                batch_size: 2
                shuffle: True
                pin_memory: True
    val:
        name: SHREC21_RCHO_Rings_RenderOnly
        args:
            csv_path: data/list/shape/1_val.csv
            root: data/shape-train-rings/
            ring_ids: [0, 3, 6]
            is_train: True
        loader:
            name: DataLoader
            args:
                batch_size: 2
                shuffle: True
                pin_memory: True
trainer:
    nepochs: 500
    val_step: 1
    log_step: 1
